services:
    service1:
        build:
            context: ./Service1/
            dockerfile: Dockerfile
        ports:
            "80:5000"
        networks:
            SFIA2Network

    service2:
        build:
            context: ./Service2/
            dockerfile: Dockerfile
        ports:
            "5001:5001"
        networks:
            SFIA2Network
    
    service3:
        build:
            context: ./Service3/
            dockerfile: Dockerfile
        ports:
            "5002:5002"
        networks: 
            SFIA2Network

    service4: 
        build: 
            context: ./service4/
            dockerfile: Dockerfile
        ports:
            "5003:5003"
        networks: 
            SFIA2Network

networks:
    SFIA2Network:
        driver: bridge

version: "3.7"
